language: c
sudo: false

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

matrix:
  fast_finish: true
  include:
    - env: BUILD=stack GHCVER=8.0.1 STACK_YAML=stack.yaml
      compiler: ": #stack 8.0.1"
      addons: {apt: {packages: [ghc-8.0.1,happy-1.19.5,alex-3.1.4,libgtk2.0-dev,libgtk-3-dev], sources: [hvr-ghc]}}

before_install:
  - unset CC
  - case "$BUILD" in
      stack)
        export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH;;
    esac
  - ./.travis-setup.sh
  - stack install alex happy
  - stack install Chart-diagrams
  - stack install gtk2hs-buildtools
  - stack install glib
  - stack install -- gtk --flag gtk:have-quartz-gtk
  - stack install Chart-cairo

install:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - case "$BUILD" in
      stack)
        stack --no-terminal test --only-dependencies;;
    esac

script:
  - set -e ; case "$BUILD" in
      stack)
        stack --no-terminal test --haddock --no-haddock-deps --ghc-options="-Werror";;
    esac
